baseUrl=https://automationexercise.com/api

productsList=/productsList
brandsList=/brandsList
searchProduct=/searchProduct
verifyLogin=/verifyLogin
createAccount=/createAccount
deleteAccount=/deleteAccount
updateAccount=/updateAccount
getUserDetail=/getUserDetailByEmail